// <auto-generated />
using System;
using C2IEDM.Web.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace C2IEDM.Web.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230911161020_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.CoordinateSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CoordinateSystems");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Line.LinePoint", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("PointId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceQuantity")
                        .HasColumnType("integer");

                    b.HasKey("LineId", "Index");

                    b.HasIndex("PointId");

                    b.ToTable("LinePoints");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.VerticalDistance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Dimension")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Superseded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VerticalDistances");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.ObjectItems.ObjectItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativeIdentificationText")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Superseded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ObjectItems");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Dead")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("C2IEDM.Web.Persistence.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.PointReference", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.CoordinateSystem");

                    b.Property<Guid>("OriginPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("XVectorPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("YVectorPointId")
                        .HasColumnType("uuid");

                    b.HasIndex("OriginPointId");

                    b.HasIndex("XVectorPointId");

                    b.HasIndex("YVectorPointId");

                    b.ToTable("PointReferences");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Location");

                    b.Property<Guid?>("LowerVerticalDistanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpperVerticalDistanceId")
                        .HasColumnType("uuid");

                    b.HasIndex("LowerVerticalDistanceId");

                    b.HasIndex("UpperVerticalDistanceId");

                    b.ToTable("GeometricVolumes");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Location");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Location");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Location");

                    b.ToTable("Surfaces");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.ObjectItems.Organisations.Organisation", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.ObjectItems.ObjectItem");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.ConeVolume", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume");

                    b.Property<Guid>("DefiningSurfaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VertexPointId")
                        .HasColumnType("uuid");

                    b.HasIndex("DefiningSurfaceId");

                    b.HasIndex("VertexPointId");

                    b.ToTable("ConeVolumes");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.SphereVolume", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume");

                    b.Property<Guid>("CentrePointId")
                        .HasColumnType("uuid");

                    b.Property<double>("RadiusDimension")
                        .HasColumnType("double precision");

                    b.HasIndex("CentrePointId");

                    b.ToTable("SphereVolumes");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.SurfaceVolume", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume");

                    b.Property<Guid>("DefiningSurfaceId")
                        .HasColumnType("uuid");

                    b.HasIndex("DefiningSurfaceId");

                    b.ToTable("SurfaceVolumes");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Points.AbsolutePoint", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point");

                    b.Property<double>("LatitudeCoordinate")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudeCoordinate")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("VerticalDistanceId")
                        .HasColumnType("uuid");

                    b.HasIndex("VerticalDistanceId");

                    b.ToTable("AbsolutePoints");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Points.RelativePoint", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point");

                    b.Property<Guid>("CoordinateSystemId")
                        .HasColumnType("uuid");

                    b.Property<double>("XCoordinateDimension")
                        .HasColumnType("double precision");

                    b.Property<double>("YCoordinateDimension")
                        .HasColumnType("double precision");

                    b.Property<double>("ZCoordinateDimension")
                        .HasColumnType("double precision");

                    b.HasIndex("CoordinateSystemId");

                    b.ToTable("RelativePoints");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.CorridorArea", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<Guid>("CenterLineId")
                        .HasColumnType("uuid");

                    b.Property<double>("WidthDimension")
                        .HasColumnType("double precision");

                    b.HasIndex("CenterLineId");

                    b.ToTable("CorridorAreas");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Ellipse", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<Guid>("CentrePointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirstConjugateDiameterPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecondConjugateDiameterPointId")
                        .HasColumnType("uuid");

                    b.HasIndex("CentrePointId");

                    b.HasIndex("FirstConjugateDiameterPointId");

                    b.HasIndex("SecondConjugateDiameterPointId");

                    b.ToTable("Ellipses");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.FanArea", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<double>("MaximumRangeDimension")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumRangeDimension")
                        .HasColumnType("double precision");

                    b.Property<double>("OrientationAngle")
                        .HasColumnType("double precision");

                    b.Property<double>("SectorSizeAngle")
                        .HasColumnType("double precision");

                    b.Property<Guid>("VertexPointId")
                        .HasColumnType("uuid");

                    b.HasIndex("VertexPointId");

                    b.ToTable("FanAreas");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.OrbitArea", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<Guid>("FirstPointId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrbitAreaAlignmentCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("SecondPointId")
                        .HasColumnType("uuid");

                    b.Property<double>("WidthDimension")
                        .HasColumnType("double precision");

                    b.HasIndex("FirstPointId");

                    b.HasIndex("SecondPointId");

                    b.ToTable("OrbitAreas");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.PolyArcArea", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<double>("ArcRadiusDimension")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BearingOriginPointId")
                        .HasColumnType("uuid");

                    b.Property<double>("BeginBearingAngle")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DefiningLineId")
                        .HasColumnType("uuid");

                    b.Property<double>("EndBearingAngle")
                        .HasColumnType("double precision");

                    b.HasIndex("BearingOriginPointId");

                    b.HasIndex("DefiningLineId");

                    b.ToTable("PolyArcAreas");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.PolygonArea", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<Guid>("BoundingLineId")
                        .HasColumnType("uuid");

                    b.HasIndex("BoundingLineId");

                    b.ToTable("PolygonAreas");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.TrackArea", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface");

                    b.Property<Guid>("BeginPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EndPointId")
                        .HasColumnType("uuid");

                    b.Property<double>("LeftWidthDimension")
                        .HasColumnType("double precision");

                    b.Property<double>("RightWidthDimension")
                        .HasColumnType("double precision");

                    b.HasIndex("BeginPointId");

                    b.HasIndex("EndPointId");

                    b.ToTable("TrackAreas");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.ObjectItems.Organisations.Unit", b =>
                {
                    b.HasBaseType("C2IEDM.Domain.Entities.ObjectItems.Organisations.Organisation");

                    b.Property<string>("FormalAbbreviatedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Line.LinePoint", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", "Line")
                        .WithMany("LinePoints")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("C2IEDM.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("C2IEDM.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("C2IEDM.Web.Persistence.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.PointReference", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.CoordinateSystem", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.PointReference", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "OriginPoint")
                        .WithMany()
                        .HasForeignKey("OriginPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "XVectorPoint")
                        .WithMany()
                        .HasForeignKey("XVectorPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "YVectorPoint")
                        .WithMany()
                        .HasForeignKey("YVectorPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginPoint");

                    b.Navigation("XVectorPoint");

                    b.Navigation("YVectorPoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Location", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.VerticalDistance", "LowerVerticalDistance")
                        .WithMany()
                        .HasForeignKey("LowerVerticalDistanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.VerticalDistance", "UpperVerticalDistance")
                        .WithMany()
                        .HasForeignKey("UpperVerticalDistanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LowerVerticalDistance");

                    b.Navigation("UpperVerticalDistance");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Location", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Location", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Location", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.ObjectItems.Organisations.Organisation", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.ObjectItems.ObjectItem", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.ObjectItems.Organisations.Organisation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.ConeVolume", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", "DefiningSurface")
                        .WithMany()
                        .HasForeignKey("DefiningSurfaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.ConeVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "VertexPoint")
                        .WithMany()
                        .HasForeignKey("VertexPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefiningSurface");

                    b.Navigation("VertexPoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.SphereVolume", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "CentrePoint")
                        .WithMany()
                        .HasForeignKey("CentrePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.SphereVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentrePoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.SurfaceVolume", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", "DefiningSurface")
                        .WithMany()
                        .HasForeignKey("DefiningSurfaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.GeometricVolume", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.GeometricVolumes.SurfaceVolume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefiningSurface");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Points.AbsolutePoint", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Points.AbsolutePoint", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.VerticalDistance", "VerticalDistance")
                        .WithMany()
                        .HasForeignKey("VerticalDistanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("VerticalDistance");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Points.RelativePoint", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.CoordinateSystems.CoordinateSystem", "CoordinateSystem")
                        .WithMany()
                        .HasForeignKey("CoordinateSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Points.RelativePoint", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinateSystem");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.CorridorArea", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", "CenterLine")
                        .WithMany()
                        .HasForeignKey("CenterLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.CorridorArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CenterLine");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Ellipse", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "CentrePoint")
                        .WithMany()
                        .HasForeignKey("CentrePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "FirstConjugateDiameterPoint")
                        .WithMany()
                        .HasForeignKey("FirstConjugateDiameterPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Ellipse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "SecondConjugateDiameterPoint")
                        .WithMany()
                        .HasForeignKey("SecondConjugateDiameterPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentrePoint");

                    b.Navigation("FirstConjugateDiameterPoint");

                    b.Navigation("SecondConjugateDiameterPoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.FanArea", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.FanArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "VertexPoint")
                        .WithMany()
                        .HasForeignKey("VertexPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VertexPoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.OrbitArea", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "FirstPoint")
                        .WithMany()
                        .HasForeignKey("FirstPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.OrbitArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "SecondPoint")
                        .WithMany()
                        .HasForeignKey("SecondPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstPoint");

                    b.Navigation("SecondPoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.PolyArcArea", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "BearingOriginPoint")
                        .WithMany()
                        .HasForeignKey("BearingOriginPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", "DefiningLine")
                        .WithMany()
                        .HasForeignKey("DefiningLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.PolyArcArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BearingOriginPoint");

                    b.Navigation("DefiningLine");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.PolygonArea", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", "BoundingLine")
                        .WithMany()
                        .HasForeignKey("BoundingLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.PolygonArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoundingLine");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.TrackArea", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "BeginPoint")
                        .WithMany()
                        .HasForeignKey("BeginPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Points.Point", "EndPoint")
                        .WithMany()
                        .HasForeignKey("EndPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.Surface", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.Geometry.Locations.Surfaces.TrackArea", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeginPoint");

                    b.Navigation("EndPoint");
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.ObjectItems.Organisations.Unit", b =>
                {
                    b.HasOne("C2IEDM.Domain.Entities.ObjectItems.Organisations.Organisation", null)
                        .WithOne()
                        .HasForeignKey("C2IEDM.Domain.Entities.ObjectItems.Organisations.Unit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C2IEDM.Domain.Entities.Geometry.Locations.Line.Line", b =>
                {
                    b.Navigation("LinePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
