// <auto-generated />
using System;
using DMI.StatDB.Persistence.EntityFrameworkCore.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMI.StatDB.Persistence.EntityFrameworkCore.SqlServer.Migrations
{
    [DbContext(typeof(StatDbContext))]
    [Migration("20220316164955_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DMI.StatDB.Domain.Entities.Position", b =>
                {
                    b.Property<int>("StatID")
                        .HasColumnType("int")
                        .HasColumnName("statid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("starttime");

                    b.Property<string>("Entity")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("entity");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("endtime");

                    b.Property<double?>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<double?>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("lat");

                    b.Property<double?>("Long")
                        .HasColumnType("float")
                        .HasColumnName("long");

                    b.HasKey("StatID", "StartTime", "Entity");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("DMI.StatDB.Domain.Entities.Station", b =>
                {
                    b.Property<int>("StatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatID"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("IcaoId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icao_id");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.HasKey("StatID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("DMI.StatDB.Domain.Entities.Position", b =>
                {
                    b.HasOne("DMI.StatDB.Domain.Entities.Station", "Station")
                        .WithMany("Positions")
                        .HasForeignKey("StatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DMI.StatDB.Domain.Entities.Station", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
